config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/:id', to: 'tasks#show', as: 'task'

  get 'new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  get 'edit/:id', to: 'tasks#edit'
  patch 'tasks/:id', to: 'tasks#update'

  get 'tasks/destroy/:id', to: 'tasks#destroy'
end

# As a user, I can list tasks
# As a user, I can view the details of a task
# As a user, I can add a new task
# As a user, I can edit a task (mark as completed / update title & details)
# As a user, I can remove a task

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  #before_action :task_params, only: [:create, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.all.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    task_params
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@task)
  end

  def edit
    @task = Task.all.find(params[:id])
  end

  def update
     @task = Task.all.find(params[:id])

     if params[:completed?] == 'yes'
        @task.completed = true
     end

     @task.update(task_params)
     redirect_to tasks_path(@task)
  end

  def destroy
    @Task = Task.all.find(params[:id])
    @Task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end


# As a user, I can list tasks
# As a user, I can view the details of a task
# As a user, I can add a new task
# As a user, I can edit a task (mark as completed / update title & details)
# As a user, I can remove a task

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details %>
  </div>

  <div class="form-group">
    <%= f.label :completed? %>
    <%= f.text_field :completed? %>
  </div>

  <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/tasks/destroy.html.erb
<%= link_to 'Delete', tasks_path(@task), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>
<%= link_to 'Tasks', tasks_path %>

app/views/tasks/index.html.erb
<h1>To Do</h1>

<% @tasks.each do |task| %>
  <h2><%= link_to "#{task.title}", task_path(task) %></h2>
  <h3>Completed: <%= task.completed ? 'Yes' : 'No' %></h3>
  <p><%= task.details %></p>
<% end %>

<%= link_to 'New task', '/new' %>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>
<%= link_to 'Tasks', tasks_path %>

app/views/tasks/show.html.erb
<h1>To Do</h1>

<h2><%= @task.title %></h2>
<h3>Completed: <%= @task.completed ? 'Yes' : 'No' %></h3>
<p><%= @task.details %></p>

<p><%= link_to 'Delete', "destroy/#{@task.id}", data: { confirm: "Are you sure?" } %></p>

<p><%= link_to 'Edit task', "/edit/#{@task.id}" %></p>

<p><%= link_to 'Tasks', tasks_path %></p>